/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class frmManHinhChinh extends javax.swing.JFrame {

    /**
     * Creates new form frmManHinhChinh
     */
    public frmManHinhChinh() {
        initComponents();
        ConnectSQL cnSQL =  new ConnectSQL();
        btnTenDangNhap.setText(frmDangNhap.TenDangNhap);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        tbaThongTin = new javax.swing.JToolBar();
        btnLogo = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnQLKhachHang = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnLoaiKH = new javax.swing.JButton();
        btnNhaCungCap = new javax.swing.JButton();
        btnQLHangHoa = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnCaLamViev = new javax.swing.JButton();
        btnBan = new javax.swing.JButton();
        btnOUT = new javax.swing.JButton();
        btnTenDangNhap = new javax.swing.JButton();
        tabThongTin = new javax.swing.JTabbedPane();
        tabList2 = new javax.swing.JTabbedPane();
        tabList1 = new javax.swing.JTabbedPane();
        mnbMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        lblThoat = new javax.swing.JCheckBoxMenuItem();
        lblDangXuat = new javax.swing.JCheckBoxMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuView = new javax.swing.JMenu();
        mNu = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Màn Hinhg Quản Lí");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tbaThongTin.setBackground(new java.awt.Color(255, 204, 204));
        tbaThongTin.setForeground(new java.awt.Color(0, 255, 153));
        tbaThongTin.setRollover(true);

        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/logoZ.png"))); // NOI18N
        btnLogo.setFocusable(false);
        btnLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });
        tbaThongTin.add(btnLogo);

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/1110.png"))); // NOI18N
        btnNhanVien.setText("QL Nhân Viên");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        tbaThongTin.add(btnNhanVien);

        btnQLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/NV.png"))); // NOI18N
        btnQLKhachHang.setText("QL Khách Hàng");
        btnQLKhachHang.setFocusable(false);
        btnQLKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKhachHangActionPerformed(evt);
            }
        });
        tbaThongTin.add(btnQLKhachHang);
        tbaThongTin.add(jLabel6);

        btnLoaiKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/LKH.png"))); // NOI18N
        btnLoaiKH.setText("QL Loại Khách Hàng");
        btnLoaiKH.setFocusable(false);
        btnLoaiKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoaiKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiKHActionPerformed(evt);
            }
        });
        tbaThongTin.add(btnLoaiKH);

        btnNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/HÀNG.png"))); // NOI18N
        btnNhaCungCap.setText("QL Kho Hàng");
        btnNhaCungCap.setFocusable(false);
        btnNhaCungCap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhaCungCap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });
        tbaThongTin.add(btnNhaCungCap);

        btnQLHangHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/kloai.png"))); // NOI18N
        btnQLHangHoa.setText("QL Loại Hàng Hóa");
        btnQLHangHoa.setFocusable(false);
        btnQLHangHoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLHangHoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHangHoaActionPerformed(evt);
            }
        });
        tbaThongTin.add(btnQLHangHoa);

        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/HOADON.png"))); // NOI18N
        btnHoaDon.setText("QL Hóa ĐƠn");
        btnHoaDon.setFocusable(false);
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        tbaThongTin.add(btnHoaDon);

        btnCaLamViev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/TIME.png"))); // NOI18N
        btnCaLamViev.setText("Ca Làm Việc");
        btnCaLamViev.setFocusable(false);
        btnCaLamViev.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaLamViev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbaThongTin.add(btnCaLamViev);

        btnBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/ban.png"))); // NOI18N
        btnBan.setText("Bàn");
        btnBan.setAlignmentX(0.5F);
        btnBan.setFocusable(false);
        btnBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbaThongTin.add(btnBan);

        btnOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/enter.png"))); // NOI18N
        btnOUT.setText("OUT");
        btnOUT.setFocusable(false);
        btnOUT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOUT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOUTActionPerformed(evt);
            }
        });
        tbaThongTin.add(btnOUT);

        btnTenDangNhap.setText("Tên Đăng Nhập");
        btnTenDangNhap.setFocusable(false);
        btnTenDangNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTenDangNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbaThongTin.add(btnTenDangNhap);

        tabThongTin.setBackground(java.awt.SystemColor.activeCaption);

        tabList2.setBackground(java.awt.SystemColor.activeCaption);
        tabThongTin.addTab("NHiệm Vụ", tabList2);

        tabList1.setBackground(new java.awt.Color(255, 204, 204));
        tabThongTin.addTab("Thông Tin", tabList1);

        mnbMenu.setBackground(java.awt.SystemColor.activeCaption);

        mnuFile.setBackground(new java.awt.Color(204, 204, 255));
        mnuFile.setText("File");

        lblThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        lblThoat.setSelected(true);
        lblThoat.setText("Thoát");
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/3330.png"))); // NOI18N
        lblThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblThoatActionPerformed(evt);
            }
        });
        mnuFile.add(lblThoat);

        lblDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        lblDangXuat.setSelected(true);
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/2220.png"))); // NOI18N
        lblDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDangXuatActionPerformed(evt);
            }
        });
        mnuFile.add(lblDangXuat);

        mnbMenu.add(mnuFile);

        mnuEdit.setBackground(new java.awt.Color(204, 204, 255));
        mnuEdit.setText("Edit");
        mnbMenu.add(mnuEdit);

        mnuView.setText("View");
        mnbMenu.add(mnuView);

        mNu.setText("Help");
        mnbMenu.add(mNu);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 1231, Short.MAX_VALUE)
            .addComponent(tabThongTin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbaThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblThoatActionPerformed
 int ketQuaNutBam = JOptionPane.showConfirmDialog(new JFrame(),
                "Bạn có Chắc Muốn thoát không?",
                "Không Xác Nhập",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ketQuaNutBam == JOptionPane.YES_OPTION){
            System.exit(0);
        }       
    }//GEN-LAST:event_lblThoatActionPerformed
int lanBamnv = 1;
    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
   pnlQLNhanVien2 pnlQLNV = new pnlQLNhanVien2(); 
          if (lanBamnv == 1) {
            pnlQLNhanVien2 nv = new pnlQLNhanVien2();
            tabThongTin.add(nv, "Quản Lý NHân Viên", 1);
            tabThongTin.setSelectedIndex(1);
            lanBamnv = 0;

        } else {
            tabThongTin.remove(1);
            lanBamnv = 1;

        }                      
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void lblDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDangXuatActionPerformed

    private void btnLoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiKHActionPerformed
       pnlLoaiKhachHang pnlQLNV = new pnlLoaiKhachHang(); 
          if (lanBamnv == 1) {
             pnlLoaiKhachHang pnlQLkh = new pnlLoaiKhachHang();
            tabThongTin.add(pnlQLkh, "Quản Lý Loại Khách Hàng", 1);
            tabThongTin.setSelectedIndex(1);
            lanBamnv = 0;

        } else {
            tabThongTin.remove(1);
            lanBamnv = 1;

        }   
    }//GEN-LAST:event_btnLoaiKHActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int ketQuaNutBam = JOptionPane.showConfirmDialog(new JFrame(),
                "Bạn có Chắc Muốn thoát không?",
                "Không Xác Nhận",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ketQuaNutBam == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing
int lanBamlogo = 1;
    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
pnlQLNhanVien2 pnlQLNV = new pnlQLNhanVien2();
       
        tabThongTin.add(pnlQLNV,"Quản Lí Nhân Viên",0);
        tabThongTin.setSelectedIndex(0);  
          if (lanBamlogo == 1) {
            pnlQLNhanVien2 nv = new pnlQLNhanVien2();
            tabThongTin.add(nv, "Quản Lý Quán Cà Phê", 1);
            tabThongTin.setSelectedIndex(1);
            lanBamlogo = 0;

        } else {
            tabThongTin.remove(1);
            lanBamlogo = 1;

        }    
    }//GEN-LAST:event_btnLogoActionPerformed
int lanBamkh = 1;
    private void btnQLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKhachHangActionPerformed
        
          if (lanBamkh == 1) {
          pnlQLKhachHang pnlQLNV = new pnlQLKhachHang();
            tabThongTin.add(pnlQLNV, "Quản Lý KHách Hàng", 1);
            tabThongTin.setSelectedIndex(1);
            lanBamkh = 0;

        } else {
            tabThongTin.remove(1);
            lanBamkh = 1;

        }  
    }//GEN-LAST:event_btnQLKhachHangActionPerformed
int lanBamncc = 1;
    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
         
       tabThongTin.setSelectedIndex(0);  
          if (lanBamncc == 1) {
          pnlQuanLiKhoHang1 pnlQLNV = new pnlQuanLiKhoHang1();
            tabThongTin.add(pnlQLNV, "Quản Lý Kho Hàng", 1);
            tabThongTin.setSelectedIndex(1);
            lanBamncc = 0;

        } else {
            tabThongTin.remove(1);
            lanBamncc = 1;

        }  
    }//GEN-LAST:event_btnNhaCungCapActionPerformed
int lanBamhgh = 1;
    private void btnQLHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHangHoaActionPerformed
       
       tabThongTin.setSelectedIndex(0);  
          if (lanBamhgh == 1) {
            pnlLoaiHangHoa pnlQLNV = new pnlLoaiHangHoa();
            tabThongTin.add(pnlQLNV, "Quản Lý Quán Cà Phê", 1);
            tabThongTin.setSelectedIndex(1);
            lanBamhgh = 0;

        } else {
            tabThongTin.remove(1);
            lanBamhgh = 1;

        }  
    }//GEN-LAST:event_btnQLHangHoaActionPerformed
 int ccc = 1;
    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
          pnlQuanLiKhoHang1 pnlQLNV = new pnlQuanLiKhoHang1();
         tabThongTin.setSelectedIndex(0);  
          if (ccc == 1) {
            pnlQLNhanVien2 nv = new pnlQLNhanVien2();
            tabThongTin.add(nv, "Quản Lý Quán Cà Phê", 1);
            tabThongTin.setSelectedIndex(1);
            ccc = 0;

        } else {
            tabThongTin.remove(1);
            ccc = 1;

        }  
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOUTActionPerformed
      frmDangNhap frmMHC = new frmDangNhap();
  frmMHC.setVisible(true);
  this.setVisible(false);
    }//GEN-LAST:event_btnOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManHinhChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnCaLamViev;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnLoaiKH;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnOUT;
    private javax.swing.JButton btnQLHangHoa;
    private javax.swing.JButton btnQLKhachHang;
    private javax.swing.JButton btnTenDangNhap;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JCheckBoxMenuItem lblDangXuat;
    private javax.swing.JCheckBoxMenuItem lblThoat;
    private javax.swing.JMenu mNu;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuView;
    private javax.swing.JTabbedPane tabList1;
    private javax.swing.JTabbedPane tabList2;
    private javax.swing.JTabbedPane tabThongTin;
    private javax.swing.JToolBar tbaThongTin;
    // End of variables declaration//GEN-END:variables
}
