/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class pnlLoaiKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form pnlLoaiHangHoa
     */
    public pnlLoaiKhachHang() {
        initComponents();
        DoDuLieuVaoTable();
    }
public void DoDuLieuVaoTable(){
        String CauLenhSQL = "Select * from LoaiKhachHang";
       ResultSet rs = ConnectSQL.ThucThiLenhReSultset(CauLenhSQL);
        
        DefaultTableModel tblModel = (DefaultTableModel)tblBangLHH.getModel();
//        xáo dữ liệu đang có trong bảng table 
        tblModel.setRowCount(0);
        Object obj[] = new Object[3];
        
        try {
            while(rs.next()){
                obj[0] = rs.getString("MaLoaiKhachHang");
                obj[1] = rs.getString("TenLoai");
                obj[2] = rs.getString("MoTa");
                tblModel.addRow(obj);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), "Lỗi truy xuất dữ liệu");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpnTeen1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpnO1 = new javax.swing.JPanel();
        lblTen1 = new javax.swing.JLabel();
        lblMOta1 = new javax.swing.JLabel();
        txtTenLoai1 = new javax.swing.JTextField();
        txtMoTa1 = new javax.swing.JTextField();
        jpnbuton1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        bang1 = new javax.swing.JScrollPane();
        tblBangLHH1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jpnTeen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnO = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        lblMOta = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpnbuton = new javax.swing.JPanel();
        btnThemn1 = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        bang = new javax.swing.JScrollPane();
        tblBangLHH = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jpnTeen1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("QUẢN LÍ  LOẠI HÀNG HÓA");

        javax.swing.GroupLayout jpnTeen1Layout = new javax.swing.GroupLayout(jpnTeen1);
        jpnTeen1.setLayout(jpnTeen1Layout);
        jpnTeen1Layout.setHorizontalGroup(
            jpnTeen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTeen1Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTeen1Layout.setVerticalGroup(
            jpnTeen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTeen1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );

        jpnO1.setBackground(new java.awt.Color(255, 255, 204));

        lblTen1.setText("Tên Loại:");

        lblMOta1.setText("Mô Tả:");

        txtTenLoai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLoai1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnO1Layout = new javax.swing.GroupLayout(jpnO1);
        jpnO1.setLayout(jpnO1Layout);
        jpnO1Layout.setHorizontalGroup(
            jpnO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnO1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnO1Layout.createSequentialGroup()
                        .addComponent(lblMOta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMoTa1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnO1Layout.createSequentialGroup()
                        .addComponent(lblTen1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jpnO1Layout.setVerticalGroup(
            jpnO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnO1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jpnO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTen1)
                    .addComponent(txtTenLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpnO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMOta1)
                    .addComponent(txtMoTa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnbuton1.setBackground(new java.awt.Color(204, 255, 204));

        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Sủa ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Xóa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnbuton1Layout = new javax.swing.GroupLayout(jpnbuton1);
        jpnbuton1.setLayout(jpnbuton1Layout);
        jpnbuton1Layout.setHorizontalGroup(
            jpnbuton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnbuton1Layout.createSequentialGroup()
                .addGroup(jpnbuton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jpnbuton1Layout.setVerticalGroup(
            jpnbuton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnbuton1Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblBangLHH1.setBackground(new java.awt.Color(153, 255, 204));
        tblBangLHH1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Loại Hàng Hóa", "Tên Loại", "Mô Tả"
            }
        ));
        tblBangLHH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangLHH1MouseClicked(evt);
            }
        });
        bang1.setViewportView(tblBangLHH1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTeen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpnO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnbuton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bang1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpnTeen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnbuton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bang1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/pexels-juan-morello-1105218.png"))); // NOI18N

        setLayout(null);

        jpnTeen.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("QUẢN LÍ  LOẠI KHÁCH HÀNG");

        javax.swing.GroupLayout jpnTeenLayout = new javax.swing.GroupLayout(jpnTeen);
        jpnTeen.setLayout(jpnTeenLayout);
        jpnTeenLayout.setHorizontalGroup(
            jpnTeenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTeenLayout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel1)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jpnTeenLayout.setVerticalGroup(
            jpnTeenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTeenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(jpnTeen);
        jpnTeen.setBounds(0, 0, 1210, 70);

        jpnO.setLayout(null);

        lblTen.setText("Tên Loại:");
        jpnO.add(lblTen);
        lblTen.setBounds(10, 60, 54, 16);

        lblMOta.setText("Mô Tả:");
        jpnO.add(lblMOta);
        lblMOta.setBounds(20, 100, 41, 16);

        txtTenLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLoaiActionPerformed(evt);
            }
        });
        jpnO.add(txtTenLoai);
        txtTenLoai.setBounds(78, 50, 190, 30);
        jpnO.add(txtMoTa);
        txtMoTa.setBounds(78, 94, 190, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/6fa9c33211ce7c08f2cc4fcef6144b7d.png"))); // NOI18N
        jpnO.add(jLabel5);
        jLabel5.setBounds(-730, -80, 1000, 562);

        add(jpnO);
        jpnO.setBounds(0, 70, 280, 190);

        jpnbuton.setBackground(new java.awt.Color(153, 255, 153));

        btnThemn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/add.png"))); // NOI18N
        btnThemn1.setText("Thêm");
        btnThemn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemn1ActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/updated.png"))); // NOI18N
        btnSua.setText("Sủa ");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnbutonLayout = new javax.swing.GroupLayout(jpnbuton);
        jpnbuton.setLayout(jpnbutonLayout);
        jpnbutonLayout.setHorizontalGroup(
            jpnbutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnbutonLayout.createSequentialGroup()
                .addGroup(jpnbutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnbutonLayout.setVerticalGroup(
            jpnbutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnbutonLayout.createSequentialGroup()
                .addComponent(btnThemn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jpnbuton);
        jpnbuton.setBounds(284, 72, 100, 189);

        tblBangLHH.setBackground(new java.awt.Color(153, 255, 204));
        tblBangLHH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Loại Hàng Hóa", "Tên Loại", "Mô Tả"
            }
        ));
        tblBangLHH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangLHHMouseClicked(evt);
            }
        });
        bang.setViewportView(tblBangLHH);

        add(bang);
        bang.setBounds(379, 72, 830, 189);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/HinhAnh/pexels-juan-morello-1105218.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, -1250, 1220, 2530);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
      int viTriDuocChon = tblBangLHH.getSelectedRow();

        if(viTriDuocChon == -1){
            JOptionPane.showMessageDialog(new JFrame(), "Bạn chưa chọn dòng để sửa");
            return; //thoat khoi ham
        }  
        
           String tenLoai = txtTenLoai.getText();
      String mota= txtMoTa.getText();
        String maLKH = tblBangLHH.getValueAt(viTriDuocChon,0).toString();
        if(tenLoai.equals("") || mota.equals("")){
           JOptionPane.showMessageDialog(new JFrame(), "Chưa Nhập Đầy Đủ Thông Tin");
       }else{
        String CauLenhSua = "UPDATE [dbo].[LoaiKhachHang]  " +
"   SET [TenLoai] = N'"+tenLoai+"'  " +
"      ,[Mota] = N'"+mota+"'  " +
" WHERE MaLoaiKhachHang = " + maLKH;
          ConnectSQL.ThucThi3Lenh(CauLenhSua);
        DoDuLieuVaoTable();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
      int DSViTriXoa [] = tblBangLHH.getSelectedRows();
        
        for(int i = DSViTriXoa.length - 1; i >= 0; i-- ){
//            DefaultTableModel tblModel = (DefaultTableModel)tblBangDuLieu.getModel();
//            tblModel.removeRow(DSViTriXoa[i]);
//          Lấy IDSanPham caanf xóa từ dòng đc chọn
            String maLKH = tblBangLHH.getValueAt(DSViTriXoa[i], 0).toString();
//            tạo lệnh xóa dựa vào IDSanPham ở trên
            String CauLenhSQL = "DELETE FROM [dbo].[LoaiKhachHang] WHERE MaLoaiKhachHang = " + maLKH;
            ConnectSQL.ThucThi3Lenh(CauLenhSQL);
            DoDuLieuVaoTable();
        } 
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemn1ActionPerformed
   
      String tenLoai = txtTenLoai.getText();
      String mota= txtMoTa.getText();
       if(tenLoai.equals("") || mota.equals("")){
           JOptionPane.showMessageDialog(new JFrame(), "Chưa Nhập Đầy Đủ Thông Tin");
       }else{
      String cauLenhThem = "INSERT INTO [dbo].[LoaiKhachHang]  " +
"           ([TenLoai]  " +
"           ,[MoTa])  " +
"     VALUES  " +
"           (N'"+tenLoai+"'  " +
"           ,N'"+mota+"  " +
"		   ')";
       ConnectSQL.ThucThi3Lenh(cauLenhThem);
           DoDuLieuVaoTable();
       } 
    }//GEN-LAST:event_btnThemn1ActionPerformed

    private void tblBangLHHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangLHHMouseClicked
        int viTriDuocChon = tblBangLHH.getSelectedRow();

   
    String tenKH = tblBangLHH.getValueAt(viTriDuocChon, 1).toString();
    txtTenLoai.setText(tenKH);
    
    String diaChi = tblBangLHH.getValueAt(viTriDuocChon, 2).toString();
    txtMoTa.setText(diaChi);
    }//GEN-LAST:event_tblBangLHHMouseClicked

    private void txtTenLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoaiActionPerformed

    private void txtTenLoai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLoai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoai1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblBangLHH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangLHH1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBangLHH1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bang;
    private javax.swing.JScrollPane bang1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemn1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpnO;
    private javax.swing.JPanel jpnO1;
    private javax.swing.JPanel jpnTeen;
    private javax.swing.JPanel jpnTeen1;
    private javax.swing.JPanel jpnbuton;
    private javax.swing.JPanel jpnbuton1;
    private javax.swing.JLabel lblMOta;
    private javax.swing.JLabel lblMOta1;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTen1;
    private javax.swing.JTable tblBangLHH;
    private javax.swing.JTable tblBangLHH1;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtMoTa1;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txtTenLoai1;
    // End of variables declaration//GEN-END:variables
}
